name: Run Main Script

on:
  push:
    branches:
      - main

jobs:
  run_main:
    name: Run Main Script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Main Script with input
      run: python main.py ${{ github.event_name == 'push' && contains(github.event.head_commit.message, 'run') && 'si' || 'no' }}
